# Generated by Django 4.2.5 on 2023-09-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='shift_time',
            field=models.TimeField(default='08:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slot',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
