# Generated by Django 4.2.5 on 2023-09-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0002_slot_shift_time_alter_slot_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='shift_time',
        ),
        migrations.AlterField(
            model_name='slot',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
