# Generated by Django 4.2.5 on 2023-09-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0003_remove_slot_shift_time_alter_slot_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalbooking',
            name='booking_date',
        ),
    ]
