# Generated by Django 4.2.5 on 2023-10-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slots', '0004_remove_historicalbooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='shifts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
